[package]
name = "altars"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.5"
fxhash = "0.2.1"
lazy_static = "1.4.0"
rustyline = "9.0.0"
substring = "1.4.5"
